# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0spSshJe5Nd46LbHqpqatLxO2fihDbw
"""



# Commented out IPython magic to ensure Python compatibility.
# #C3:
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# import joblib
# import warnings
# warnings.filterwarnings('ignore')
# 
# # ============================================================
# # PAGE CONFIG
# # ============================================================
# st.set_page_config(
#     page_title="Fraud Detection Dashboard",
#     page_icon="🔍",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # ============================================================
# # LOAD DATA & MODELS
# # ============================================================
# @st.cache_data
# def load_data():
#     return pd.read_csv('/content/drive/MyDrive/Fraud Detection/df_clean_features.csv')
# 
# @st.cache_resource
# def load_models():
#     rf  = joblib.load('/content/drive/MyDrive/Fraud Detection/rf_model.pkl')
#     xgb = joblib.load('/content/drive/MyDrive/Fraud Detection/xgb_model.pkl')
#     return rf, xgb
# 
# df = load_data()
# rf_model, xgb_model = load_models()
# 
# FEATURES = [
#     'amount', 'amountLog', 'amountToBalanceRatio',
#     'isRiskyType', 'type_TRANSFER', 'type_CASH_OUT',
#     'type_PAYMENT', 'type_CASH_IN', 'type_DEBIT',
#     'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest',
#     'balanceDiffOrg_clean', 'balanceDiffDest_clean', 'balanceDiscrepancyOrg',
#     'drainRatio', 'destBalanceChangeRatio',
#     'isAccountDrained', 'isDrainedRiskyType', 'isDestBalanceZero',
#     'isFullFraudPattern', 'origIsCustomer', 'destIsCustomer',
#     'destIsMerchant', 'destTransactionCount'
# ]
# 
# # ============================================================
# # SIDEBAR
# # ============================================================
# st.sidebar.image("https://img.icons8.com/color/96/bank.png", width=80)
# st.sidebar.title("Fraud Detection")
# st.sidebar.markdown("*Bank Transaction Analytics*")
# st.sidebar.markdown("---")
# 
# page = st.sidebar.radio(
#     "Navigate",
#     ["Overview", "EDA", "Time Analysis", "Model Performance", "Fraud Predictor"]
# )
# 
# st.sidebar.markdown("---")
# st.sidebar.markdown(f"**Dataset:** {len(df):,} transactions")
# st.sidebar.markdown(f"**Fraud cases:** {df['isFraud'].sum():,}")
# st.sidebar.markdown(f"**Fraud rate:** {df['isFraud'].mean()*100:.4f}%")
# 
# # ============================================================
# # PAGE 1 — OVERVIEW
# # ============================================================
# if page == "Overview":
#     st.title("🔍 Fraud Detection Dashboard")
#     st.markdown("### Bank Transaction Fraud Analytics — PaySim Dataset")
#     st.markdown("---")
# 
#     col1, col2, col3, col4 = st.columns(4)
#     with col1:
#         st.metric("Total Transactions", f"{len(df):,}")
#     with col2:
#         st.metric("Fraud Cases", f"{df['isFraud'].sum():,}")
#     with col3:
#         st.metric("Fraud Rate", f"{df['isFraud'].mean()*100:.4f}%")
#     with col4:
#         fraud_value = df[df['isFraud']==1]['amount'].sum()
#         st.metric("Total Fraud Value", f"${fraud_value/1e9:.2f}B")
# 
#     st.markdown("---")
# 
#     col1, col2, col3, col4 = st.columns(4)
#     with col1:
#         st.metric("Existing System Detection", "0.19%",
#                   delta="-99.81%", delta_color="inverse")
#     with col2:
#         st.metric("ML Model Detection", "99.95%", delta="+99.76%")
#     with col3:
#         st.metric("False Positives", "0")
#     with col4:
#         st.metric("Improvement", "526x better")
# 
#     st.markdown("---")
#     st.subheader("📊 Model Comparison")
#     comparison = pd.DataFrame({
#         'Metric': ['Fraud Caught', 'Fraud Missed', 'False Positives',
#                    'Recall', 'Precision', 'ROC-AUC'],
#         'Rule-Based System': ['16', '8,197', '0', '0.19%', '100%', 'N/A'],
#         'Random Forest':     ['3,734', '2', '0', '99.95%', '100%', '1.0000'],
#         'XGBoost':           ['3,734', '2', '0', '99.95%', '100%', '1.0000']
#     })
#     st.dataframe(comparison, use_container_width=True, hide_index=True)
# 
#     st.markdown("---")
#     st.subheader("💳 Fraud by Transaction Type")
#     type_fraud = df.groupby('type').agg(
#         Total=('isFraud','count'),
#         Fraud=('isFraud','sum')
#     ).reset_index()
#     type_fraud['FraudRate'] = (type_fraud['Fraud']/type_fraud['Total']*100).round(4)
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         fig = px.bar(type_fraud.sort_values('Fraud', ascending=False),
#                      x='type', y='Fraud',
#                      title='Fraud Cases by Type',
#                      color='Fraud',
#                      color_continuous_scale='Reds')
#         st.plotly_chart(fig, use_container_width=True)
#     with col2:
#         fig = px.bar(type_fraud.sort_values('FraudRate', ascending=False),
#                      x='type', y='FraudRate',
#                      title='Fraud Rate by Type (%)',
#                      color='FraudRate',
#                      color_continuous_scale='Oranges')
#         st.plotly_chart(fig, use_container_width=True)
# 
#     st.markdown("---")
#     st.subheader("🔑 Key Findings")
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.info("**Two-Type Fraud Rule**\n\nOnly TRANSFER and CASH_OUT carry fraud. PAYMENT, CASH_IN and DEBIT have zero fraud across 3.6M transactions.")
#     with col2:
#         st.warning("**Account Drain Pattern**\n\n98% of fraud transactions drain the origin account to exactly zero. Fraudsters take everything in one hit.")
#     with col3:
#         st.error("**Broken Flag System**\n\nExisting system catches only 16 of 8,213 fraud cases — 0.19% detection rate. ML model catches 99.95%.")
# 
# # ============================================================
# # PAGE 2 — EDA
# # ============================================================
# elif page == "EDA":
#     st.title("📊 Exploratory Data Analysis")
#     st.markdown("---")
# 
#     tab1, tab2, tab3 = st.tabs(["Class Imbalance", "Amount Analysis", "Balance Analysis"])
# 
#     with tab1:
#         st.subheader("Class Imbalance")
#         col1, col2 = st.columns(2)
#         with col1:
#             fraud_counts = df['isFraud'].value_counts()
#             fig = px.bar(
#                 x=['Legitimate', 'Fraud'],
#                 y=fraud_counts.values,
#                 color=['Legitimate', 'Fraud'],
#                 color_discrete_map={'Legitimate':'steelblue','Fraud':'#E24B4A'},
#                 title='Transaction Count by Class'
#             )
#             st.plotly_chart(fig, use_container_width=True)
#         with col2:
#             fig = px.pie(
#                 values=fraud_counts.values,
#                 names=['Legitimate', 'Fraud'],
#                 title='Class Distribution',
#                 color_discrete_sequence=['steelblue','#E24B4A'],
#                 hole=0.5
#             )
#             st.plotly_chart(fig, use_container_width=True)
#         st.info("**99.87% legitimate vs 0.13% fraud** — extreme class imbalance. For every 1 fraud there are 773 legitimate transactions.")
# 
#     with tab2:
#         st.subheader("Amount Analysis")
#         col1, col2 = st.columns(2)
#         with col1:
#             amount_stats = pd.DataFrame({
#                 'Metric': ['Mean', 'Median', 'Max'],
#                 'Legitimate': ['$178K', '$74K', '$92.4M'],
#                 'Fraud': ['$1.47M', '$441K', '$10M']
#             })
#             st.dataframe(amount_stats, use_container_width=True, hide_index=True)
#             st.warning("Fraud transactions are **8x larger** on average than legitimate ones.")
#         with col2:
#             fig = px.box(
#                 df.sample(10000, random_state=42),
#                 x='isFraud', y='amount',
#                 color='isFraud',
#                 title='Amount Distribution — Fraud vs Legitimate',
#                 color_discrete_map={0:'steelblue', 1:'#E24B4A'},
#                 labels={'isFraud': 'Is Fraud', 'amount': 'Amount ($)'}
#             )
#             fig.update_layout(yaxis_type='log')
#             st.plotly_chart(fig, use_container_width=True)
# 
#     with tab3:
#         st.subheader("Balance Analysis")
#         col1, col2 = st.columns(2)
#         with col1:
#             drain_data = pd.DataFrame({
#                 'Class': ['Legitimate', 'Fraud'],
#                 'Drained (%)': [72.6, 98.0],
#                 'Not Drained (%)': [27.4, 2.0]
#             })
#             fig = px.bar(drain_data, x='Class',
#                         y=['Drained (%)', 'Not Drained (%)'],
#                         title='Account Drain Rate — Fraud vs Legitimate',
#                         color_discrete_map={'Drained (%)':'#E24B4A',
#                                           'Not Drained (%)':'steelblue'})
#             st.plotly_chart(fig, use_container_width=True)
#         with col2:
#             feature_rates = pd.DataFrame({
#                 'Feature': ['isAccountDrained', 'isDrainedRiskyType', 'isFullFraudPattern'],
#                 'Fraud Rate (%)': [0.53, 0.68, 76.03]
#             })
#             fig = px.bar(feature_rates, x='Feature', y='Fraud Rate (%)',
#                         title='Fraud Rate by Engineered Feature',
#                         color='Fraud Rate (%)',
#                         color_continuous_scale='Reds')
#             st.plotly_chart(fig, use_container_width=True)
#         st.success("**isFullFraudPattern** achieves 76% fraud rate — combining account drain + risky type + destination balance zero.")
# 
# # ============================================================
# # PAGE 3 — TIME ANALYSIS
# # ============================================================
# elif page == "Time Analysis":
#     st.title("⏱️ Time Analysis")
#     st.markdown("---")
# 
#     step_stats = df.groupby('step').agg(
#         TotalTransactions=('isFraud','count'),
#         FraudTransactions=('isFraud','sum')
#     ).reset_index()
#     step_stats['FraudRate'] = (step_stats['FraudTransactions'] /
#                                step_stats['TotalTransactions'] * 100).round(4)
#     step_stats['RollingFraud'] = step_stats['FraudTransactions'].rolling(24, center=True).mean()
#     step_stats['RollingRate']  = step_stats['FraudRate'].rolling(24, center=True).mean()
# 
#     fig = px.line(step_stats, x='step', y='TotalTransactions',
#                   title='Total Transaction Volume per Step',
#                   color_discrete_sequence=['steelblue'])
#     fig.add_vline(x=400, line_dash='dot', line_color='gray',
#                   annotation_text='Volume drops')
#     st.plotly_chart(fig, use_container_width=True)
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         fig = px.bar(step_stats, x='step', y='FraudTransactions',
#                      title='Fraud Count per Step',
#                      color_discrete_sequence=['#E24B4A'])
#         fig.add_hline(y=step_stats['FraudTransactions'].mean(),
#                       line_dash='dash', line_color='green',
#                       annotation_text=f"Mean: {step_stats['FraudTransactions'].mean():.1f}")
#         st.plotly_chart(fig, use_container_width=True)
#     with col2:
#         fig = go.Figure()
#         fig.add_trace(go.Scatter(
#             x=step_stats['step'], y=step_stats['FraudRate'],
#             mode='lines', name='Per step',
#             line=dict(color='#9B30A0', width=0.8), opacity=0.3))
#         fig.add_trace(go.Scatter(
#             x=step_stats['step'], y=step_stats['RollingRate'],
#             mode='lines', name='24-step avg',
#             line=dict(color='#6A1070', width=2)))
#         fig.update_layout(title='Fraud Rate per Step (%) with Rolling Average')
#         st.plotly_chart(fig, use_container_width=True)
# 
#     st.markdown("---")
#     st.subheader("🔺 Spike Detection (Volume Filtered)")
# 
#     min_volume = st.slider("Minimum transaction volume for spike detection",
#                            100, 5000, 1000, 100)
# 
#     filtered  = step_stats[step_stats['TotalTransactions'] >= min_volume]
#     mean_f    = filtered['FraudTransactions'].mean()
#     std_f     = filtered['FraudTransactions'].std()
#     threshold = mean_f + 2 * std_f
#     spikes    = filtered[filtered['FraudTransactions'] >= threshold]
# 
#     col1, col2, col3 = st.columns(3)
#     with col1:
#         st.metric("Mean fraud/step", f"{mean_f:.1f}")
#     with col2:
#         st.metric("Spike threshold", f"{threshold:.1f}")
#     with col3:
#         st.metric("Spikes detected", len(spikes))
# 
#     fig = go.Figure()
#     fig.add_trace(go.Scatter(
#         x=step_stats['step'], y=step_stats['FraudTransactions'],
#         mode='lines', name='Fraud per step',
#         line=dict(color='steelblue', width=0.9)))
#     fig.add_trace(go.Scatter(
#         x=spikes['step'], y=spikes['FraudTransactions'],
#         mode='markers+text',
#         marker=dict(color='red', size=8),
#         text=spikes['FraudTransactions'].astype(str),
#         textposition='top center',
#         name='Spike'))
#     fig.add_hline(y=threshold, line_dash='dash', line_color='orange',
#                   annotation_text=f'Threshold ({threshold:.1f})')
#     fig.add_hline(y=mean_f, line_dash='dash', line_color='green',
#                   annotation_text=f'Mean ({mean_f:.1f})')
#     fig.update_layout(title='Fraud Spike Detection (Volume Filtered)')
#     st.plotly_chart(fig, use_container_width=True)
# 
#     st.info("**Key insight:** Fraud COUNT is stationary throughout all 743 steps. The fraud RATE is misleading — it's driven by transaction volume, not fraud behaviour.")
# 
# # ============================================================
# # PAGE 4 — MODEL PERFORMANCE
# # ============================================================
# elif page == "Model Performance":
#     st.title("🤖 Model Performance")
#     st.markdown("---")
# 
#     st.subheader("Model Comparison")
#     comparison = pd.DataFrame({
#         'Metric': ['Fraud Caught', 'Fraud Missed', 'False Positives',
#                    'Recall', 'Precision', 'ROC-AUC'],
#         'Rule-Based System': ['16', '8,197', '0', '0.19%', '100%', 'N/A'],
#         'Random Forest':     ['3,734', '2', '0', '99.95%', '100%', '1.0000'],
#         'XGBoost':           ['3,734', '2', '0', '99.95%', '100%', '1.0000']
#     })
#     st.dataframe(comparison, use_container_width=True, hide_index=True)
# 
#     st.markdown("---")
#     col1, col2 = st.columns(2)
#     with col1:
#         fig = px.bar(
#             x=['Rule-Based', 'Random Forest', 'XGBoost'],
#             y=[0.19, 99.95, 99.95],
#             title='Recall Comparison (%)',
#             color=['Rule-Based', 'Random Forest', 'XGBoost'],
#             color_discrete_map={
#                 'Rule-Based':'gray',
#                 'Random Forest':'steelblue',
#                 'XGBoost':'#E24B4A'
#             }
#         )
#         fig.update_layout(showlegend=False)
#         st.plotly_chart(fig, use_container_width=True)
#     with col2:
#         fig = px.bar(
#             x=['Rule-Based', 'Random Forest', 'XGBoost'],
#             y=[16, 3734, 3734],
#             title='Fraud Cases Caught',
#             color=['Rule-Based', 'Random Forest', 'XGBoost'],
#             color_discrete_map={
#                 'Rule-Based':'gray',
#                 'Random Forest':'steelblue',
#                 'XGBoost':'#E24B4A'
#             }
#         )
#         fig.update_layout(showlegend=False)
#         st.plotly_chart(fig, use_container_width=True)
# 
#     st.markdown("---")
#     st.subheader("🎯 Feature Importance — XGBoost")
#     feat_importance = pd.DataFrame({
#         'Feature': FEATURES,
#         'Importance': xgb_model.feature_importances_
#     }).sort_values('Importance', ascending=True).tail(15)
# 
#     fig = px.bar(feat_importance, x='Importance', y='Feature',
#                  orientation='h',
#                  title='Top 15 Feature Importances',
#                  color='Importance',
#                  color_continuous_scale='Reds')
#     st.plotly_chart(fig, use_container_width=True)
# 
#     st.markdown("---")
#     st.subheader("💡 How the Model Decides")
#     col1, col2 = st.columns(2)
#     with col1:
#         st.error("**balanceDiscrepancyOrg (61.5%)**\n\nMeasures whether the amount transferred matches the balance reduction. In fraud, these match perfectly — full drain.")
#     with col2:
#         st.warning("**isAccountDrained (32.5%)**\n\nBinary flag — was the origin account completely emptied? 98% of fraud drains to exactly zero.")
# 
# # ============================================================
# # PAGE 5 — FRAUD PREDICTOR
# # ============================================================
# elif page == "Fraud Predictor":
#     st.title("🎯 Fraud Predictor")
#     st.markdown("Enter transaction details to get a fraud probability score.")
#     st.markdown("---")
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         st.subheader("Transaction Details")
#         txn_type = st.selectbox("Transaction Type",
#                                 ['TRANSFER', 'CASH_OUT', 'PAYMENT', 'CASH_IN', 'DEBIT'])
#         amount = st.number_input("Amount ($)", min_value=0.0,
#                                   value=50000.0, step=1000.0)
#         oldbalanceOrg = st.number_input("Origin Opening Balance ($)",
#                                          min_value=0.0, value=100000.0, step=1000.0)
#         newbalanceOrig = st.number_input("Origin Closing Balance ($)",
#                                           min_value=0.0, value=50000.0, step=1000.0)
#     with col2:
#         st.subheader("Account Details")
#         oldbalanceDest = st.number_input("Destination Opening Balance ($)",
#                                           min_value=0.0, value=0.0, step=1000.0)
#         newbalanceDest = st.number_input("Destination Closing Balance ($)",
#                                           min_value=0.0, value=50000.0, step=1000.0)
#         dest_type = st.selectbox("Destination Account Type",
#                                   ['Customer (C)', 'Merchant (M)'])
#         dest_txn_count = st.number_input("Destination Transaction Count",
#                                           min_value=1, value=1, step=1)
# 
#     st.markdown("---")
#     model_choice = st.radio("Select Model", ['XGBoost', 'Random Forest'],
#                              horizontal=True)
# 
#     if st.button("🔍 Predict", use_container_width=True):
#         # engineer features
#         balanceDiffOrg        = oldbalanceOrg - newbalanceOrig
#         balanceDiffDest       = newbalanceDest - oldbalanceDest
#         balanceDiffOrg_clean  = max(0, balanceDiffOrg)
#         balanceDiffDest_clean = max(0, balanceDiffDest)
#         balanceDiscrepancyOrg = abs(amount - balanceDiffOrg_clean)
#         drainRatio            = balanceDiffOrg_clean / oldbalanceOrg if oldbalanceOrg > 0 else 0
#         destBalanceChangeRatio = balanceDiffDest_clean / oldbalanceDest if oldbalanceDest > 0 else 0
#         amountToBalanceRatio  = min(1.0, amount / oldbalanceOrg) if oldbalanceOrg > 0 else 0
#         isAccountDrained      = int(newbalanceOrig == 0 and oldbalanceOrg > 0)
#         isRiskyType           = int(txn_type in ['TRANSFER', 'CASH_OUT'])
#         isDrainedRiskyType    = int(isAccountDrained and isRiskyType)
#         isDestBalanceZero     = int(newbalanceDest == 0)
#         isFullFraudPattern    = int(isAccountDrained and isRiskyType and isDestBalanceZero)
#         destIsCustomer        = int(dest_type == 'Customer (C)')
#         destIsMerchant        = int(dest_type == 'Merchant (M)')
# 
#         input_data = pd.DataFrame([{
#             'amount': amount,
#             'amountLog': np.log1p(amount),
#             'amountToBalanceRatio': amountToBalanceRatio,
#             'isRiskyType': isRiskyType,
#             'type_TRANSFER': int(txn_type == 'TRANSFER'),
#             'type_CASH_OUT': int(txn_type == 'CASH_OUT'),
#             'type_PAYMENT': int(txn_type == 'PAYMENT'),
#             'type_CASH_IN': int(txn_type == 'CASH_IN'),
#             'type_DEBIT': int(txn_type == 'DEBIT'),
#             'oldbalanceOrg': oldbalanceOrg,
#             'newbalanceOrig': newbalanceOrig,
#             'oldbalanceDest': oldbalanceDest,
#             'newbalanceDest': newbalanceDest,
#             'balanceDiffOrg_clean': balanceDiffOrg_clean,
#             'balanceDiffDest_clean': balanceDiffDest_clean,
#             'balanceDiscrepancyOrg': balanceDiscrepancyOrg,
#             'drainRatio': drainRatio,
#             'destBalanceChangeRatio': destBalanceChangeRatio,
#             'isAccountDrained': isAccountDrained,
#             'isDrainedRiskyType': isDrainedRiskyType,
#             'isDestBalanceZero': isDestBalanceZero,
#             'isFullFraudPattern': isFullFraudPattern,
#             'origIsCustomer': 1,
#             'destIsCustomer': destIsCustomer,
#             'destIsMerchant': destIsMerchant,
#             'destTransactionCount': dest_txn_count
#         }])
# 
#         model = xgb_model if model_choice == 'XGBoost' else rf_model
#         proba      = model.predict_proba(input_data)[0][1]
#         prediction = model.predict(input_data)[0]
# 
#         st.markdown("---")
#         st.subheader("Prediction Result")
# 
#         col1, col2, col3 = st.columns(3)
#         with col1:
#             st.metric("Fraud Probability", f"{proba*100:.2f}%")
#         with col2:
#             st.metric("Prediction", "🚨 FRAUD" if prediction == 1 else "✅ LEGITIMATE")
#         with col3:
#             st.metric("Model Used", model_choice)
# 
#         fig = go.Figure(go.Indicator(
#             mode="gauge+number",
#             value=proba * 100,
#             title={'text': "Fraud Probability (%)"},
#             gauge={
#                 'axis': {'range': [0, 100]},
#                 'bar': {'color': "#E24B4A" if proba > 0.5 else "steelblue"},
#                 'steps': [
#                     {'range': [0, 30],  'color': '#EAF3DE'},
#                     {'range': [30, 70], 'color': '#FAEEDA'},
#                     {'range': [70, 100],'color': '#FCEBEB'}
#                 ],
#                 'threshold': {
#                     'line': {'color': "red", 'width': 4},
#                     'thickness': 0.75,
#                     'value': 50
#                 }
#             }
#         ))
#         st.plotly_chart(fig, use_container_width=True)
# 
#         st.subheader("🔍 Why this prediction?")
#         col1, col2, col3 = st.columns(3)
#         with col1:
#             st.metric("Account Drained",
#                       "Yes ⚠️" if isAccountDrained else "No ✅")
#         with col2:
#             st.metric("Risky Type",
#                       "Yes ⚠️" if isRiskyType else "No ✅")
#         with col3:
#             st.metric("Full Fraud Pattern",
#                       "Yes 🚨" if isFullFraudPattern else "No ✅")
# 
#         if prediction == 1:
#             st.error("🚨 This transaction shows characteristics consistent with fraud. Recommend blocking and investigation.")
#         else:
#             st.success("✅ This transaction appears legitimate based on the model's analysis.")